### ISSUE TITLE
Could not load type 'MyCouch.QueryParametersConfigurator' from assembly 'MyCouch.Net45, Version=3.1.1.39083, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by dannykay1710** [danielwertheim/mycouch.aspnet.identity#2]
Can no longer use the identity provider if you update MyCouch to a later version as the Identity provider seems to depend on a specific version.

Might be able to work around this with a dependency redirect however I had no luck and ended up updating all NuGet packages in source project and re-compiling.

**Comment by reddyBell** [comment]
Same for me here, I am totally stuck on my project
